In [1]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path.cwd().parent
DATA_DIR = BASE_DIR / "data"
EXTRACTED_JSONL = DATA_DIR / "extracted" / "extracted_metadata_20260402_104557.jsonl"
ORIGIN_CSV = DATA_DIR / "data_cleaned.csv"

In [2]:
df_extracted = pd.read_json(EXTRACTED_JSONL, lines=True)
df_origin = pd.read_csv(ORIGIN_CSV)
merged_df = pd.merge(df_origin, df_extracted, left_on="id", right_on="source_id", how="inner")
merged_df = merged_df.drop(columns=["source_id"])

In [3]:
merged_df.columns

Index(['description', 'museumName', 'pictureIds', 'imgUrl', 'name', 'id',
       'yearName', 'size', 'collectionTexture', 'local_image_paths', 'era',
       'culture', 'decoration', 'shape_feature', 'texture', 'root_shape',
       'condition', 'original_name'],
      dtype='object')

In [ ]:
merged_df.drop(columns=["pictureIds","imgUrl","yearName","original_name"],inplace=True)
merged_df = merged_df[[
    'id', 'name',
    'era', 'culture', 'decoration', 'shape_feature','texture', 'root_shape',
    'condition',
    'size', 'description', 'collectionTexture',
    'museumName', 'local_image_paths']]
merged_df.head(5)

,id,name,era,culture,decoration,shape_feature,texture,root_shape,condition,size,description,collectionTexture,museumName,local_image_paths
0,17A11AE71F30477DBB23A3D643557533,新石器时代大汶口文化彩绘陶罐,新石器时代,大汶口文化,彩绘,None,陶,罐,None,口径:7.5，底径:5.7，腹径：10.8,通体饰弧线三角纹和太阳纹。,陶,淄博市博物馆,images\17A11AE71F30477DBB23A3D643557533_0.jpg|...
1,4c168d7fe4494882bc97ddebc35e5f5a,新石器时代龙山文化泥质黑陶单把杯,新石器时代,龙山文化,None,单把,泥质黑陶,杯,None,高11.9， 口径7.8， 底径5.2,泥质黑陶，器表光滑，侈口，高颈，腹深且鼓，腹下部内收，平底。腹一侧有带式把。腹颈之间饰弦纹，...,陶,临沂市博物馆,images\4c168d7fe4494882bc97ddebc35e5f5a_0.JPG
2,F50A76B69A4D46CC989635E26BAEADC2,新石器时代龙山文化白陶鬹,新石器时代,龙山文化,None,None,白陶,鬹,None,NaN,最初是炊具，用于煮水或煮酒，后来演变为礼器。白陶是以瓷土和高岭土为原料，在1200度左右的温...,陶,淄博市陶瓷博物馆,images\F50A76B69A4D46CC989635E26BAEADC2_0.jpg|...
3,a2a6b23d55324997b5d72e8361811d22,新石器时代龙山文化泥质黑陶单把杯,新石器时代,龙山文化,None,单把,泥质黑陶,杯,None,高13.1cm口径7.7cm腹围10.8cm,泥质黑陶。口微侈，颈微内曲，斜肩，圆鼓腹，下收为平底，宽带式把自腹向上弯曲高出口沿与口内壁相...,陶,临沂市博物馆,images\a2a6b23d55324997b5d72e8361811d22_0.JPG|...
4,c209f3fbf25d42d5a69f52baa7815426,红陶鬶,None,None,None,None,红陶,鬶,None,NaN,未定级，长：19.4厘米，宽：15.8厘米，高：41厘米。\r\n夹砂红陶，冲天流，细长颈，...,NaN,城子崖遗址博物馆,images\c209f3fbf25d42d5a69f52baa7815426_0.JPG

In [5]:
# import openpyxl
# OUTPUT_DIR = DATA_DIR / "extracted"
# OUTPUT_XLSX = OUTPUT_DIR / "merged_data.xlsx"
# merged_df.to_excel(OUTPUT_XLSX, index=False)

In [ ]:
shape_feature_with_root = merged_df[['shape_feature', 'root_shape']].value_counts().reset_index(name='频数')
shape_feature_with_root.head(20)

   shape_feature root_shape   频数
0             高柄          杯  218
1             筒形          杯  124
2             双耳          壶   86
3             单耳          杯   75
4             双耳          罐   61
5             高柄          豆   48
6             背壶          壶   30
7             单把          杯   23
8             罐形          鼎   22
9             觯形          壶   17
10            单耳          罐   16
11            折腹          鼎   16
12            三足          器   13
13        薄胎, 高柄          杯   10
14            单耳          壶   10
15            袋足          鬶   10
16            实足          鬶    8
17            双耳          杯    8
18             背          壶    8
19            三足          盆    8

In [16]:
shape_feature_to_root = pd.crosstab(merged_df['shape_feature'], merged_df['root_shape'], normalize='index')
shape_feature_to_root_pct = (shape_feature_to_root * 100).round(2)
shape_feature_to_root_pct.loc["高柄"].sort_values(ascending=False)[lambda x: x > 0]

root_shape
杯     79.56
豆     17.52
盖杯     1.82
豆足     0.36
壶      0.36
套杯     0.36
Name: 高柄, dtype: float64